name: Docker Hub Build and Push

on:
  push:
    branches:
      - main  # Faqat main branchga push qilinganda ishlaydi

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Repository'ni klonlash
      - name: Checkout code
        uses: actions/checkout@v3

      # Dockerni sozlash
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Docker tasvirini yaratish
      - name: Build and Push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: yourusername/yourrepository:latest
